// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbBxXDrxJCmlpOOkZGMYwEhl1VZgQQM78',
    appId: '1:720242089725:web:30878f4643f39b9e2ba894',
    messagingSenderId: '720242089725',
    projectId: 'canvas-5908d',
    authDomain: 'canvas-5908d.firebaseapp.com',
    storageBucket: 'canvas-5908d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEKOZcOkAWWRgsqN9erVyRkDf69FwvkD4',
    appId: '1:720242089725:android:30e9dc1165677e5f2ba894',
    messagingSenderId: '720242089725',
    projectId: 'canvas-5908d',
    storageBucket: 'canvas-5908d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKJrY6I9JDlC4xwt8EluiqcYory44Eg4M',
    appId: '1:720242089725:ios:1acc4c88ef4a796b2ba894',
    messagingSenderId: '720242089725',
    projectId: 'canvas-5908d',
    storageBucket: 'canvas-5908d.firebasestorage.app',
    iosBundleId: 'com.example.canvasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKJrY6I9JDlC4xwt8EluiqcYory44Eg4M',
    appId: '1:720242089725:ios:1acc4c88ef4a796b2ba894',
    messagingSenderId: '720242089725',
    projectId: 'canvas-5908d',
    storageBucket: 'canvas-5908d.firebasestorage.app',
    iosBundleId: 'com.example.canvasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbBxXDrxJCmlpOOkZGMYwEhl1VZgQQM78',
    appId: '1:720242089725:web:2fd03c29021845462ba894',
    messagingSenderId: '720242089725',
    projectId: 'canvas-5908d',
    authDomain: 'canvas-5908d.firebaseapp.com',
    storageBucket: 'canvas-5908d.firebasestorage.app',
  );
}
